# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eda261d190077ffb0520e66614be14c036453afd969e03704d5cb05c6ddad7775f1db99e0938a08df20440714f63e6c1f932d25e7518c9673581e02070cd77d

test:
  secret_key_base: 57e69b746f31bf246caa0baedf215ce63abd6efed1fa5af38f607d931b618422f03613d989c386006ed61ad76f818f2bba523f7712b273f98a2a84803999037c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
