Video.create(video_title: 'Dota 2',video_url: 'https://www.youtube.com/watch?v=XxOIVBM8tZM',video_description: 'Shopify Rebellion vs TSM')
Video.create(video_title: 'Dota 2',video_url: 'https://www.youtube.com/watch?v=t_DQsY4vg9E',video_description: 'OG vs Tundra')
Video.create(video_title: 'Dota 2',video_url: 'https://www.youtube.com/watch?v=XxOIVBM8tZM',video_description: 'Shopify Rebellion vs TSM')
Video.create(video_title: 'Dota 2',video_url: 'https://www.youtube.com/watch?v=XxOIVBM8tZM',video_description: 'Shopify Rebellion vs TSM')
Video.create(video_title: 'Dota 2',video_url: 'https://www.youtube.com/watch?v=XxOIVBM8tZM',video_description: 'Shopify Rebellion vs TSM')
